server.port: 8081

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
      username: joaovq
      password: 156678894vitor
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
#        create para criar; update para atualizar ; drop para apagar sempre que rodar.
        properties:
          hibernate.format_sql: true
  logging:
      level:
        org:
          hibernate:
            type: trace